Repository juanpujol/polyunion, pull requests merged in 2024-03, with the labels that each got.

#2 refactor: import turfjs modules individually
  package-lock.json
  package.json
  src/index.test.ts
  src/index.ts
Labels: enhancement

#4 feat: Add unit test workflow
  .github/workflows/unit-tests.yml
Labels: enhancement

#6 Release v0.0.2
  .github/workflows/npm-publish.yml
  CHANGELOG.md
  package.json
Labels: chore

#7 Release v0.1.0
  .eslintignore
  .eslintrc.cjs
  .github/workflows/unit-tests.yml
  .npmignore
  .prettierrc
  .vscode/settings.json
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
  src/index.ts
  tsup.config.ts
Labels: chore

#8 Release v0.1.1
  .npmignore
  CHANGELOG.md
  images/example-01.webp
  package.json
Labels: chore

#9 Release v0.1.2
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
  src/index.test.ts
  src/index.ts
Labels: chore

#10 Testing Merging circles polyunion
  .gitignore
  .vscode/settings.json
  package-lock.json
  package.json
  src/index.ts
  tests/fixtures/data.json
  tests/helpers.ts
  tests/index.test.ts
  tsconfig.json
Labels: bug

#11 Release v0.1.3
  .gitignore
  .vscode/settings.json
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
  src/index.ts
  tests/fixtures/data.json
  tests/helpers.ts
  tests/index.test.ts
  tsconfig.json
Labels: chore
